# List of questions for outlier detection
source_form_outlier_questions:
  - "YOUR_QUESTION_1"
  - "YOUR_QUESTION_2"

# Specify outlier detection period
activity_outlier_startdate: "2023-11-01"
activity_outlier_enddate: "2023-12-01"

